### ISSUE TITLE
Persist CurrentAttributes

### ISSUE THREAD

**Issue by javierav** [basecamp/solid_queue#100]
In many cases it is necessary for a job to have access to the context in which the job is queued, for example to the current user of the request. Rails implements CurrentAttributes for these types of operations but they do not persist across jobs.

For example, Sidekiq implements it through middleware https://www.rubydoc.info/gems/sidekiq/Sidekiq/CurrentAttributes

**Comment by jmschneider** [comment]
I realize this is an old, closed issue but I did want to add some additional thoughts to it. There is some contextual data that is useful to automatically pass through that, while it can be manually passed for each job, can become quite cumbersome. Often times this context is handled in an automated fashion within the web request cycle but requires more attention when working with background jobs. Supporting middleware would allow developers to add this kind of automatic context when it makes sense for their application. The two main use cases that come to mind are:

1. `request_id` - When reviewing logs it can be helpful to group together entries that relate to the same request. By automatically passing the `request_id` from the web worker to the background worker (and from background worker to background worker), we can more easily understand the chain of events. From a developers perspective, this is typically something that is set automatically before any application specific code and something you don't have to think about. Since we are somewhat "trained" not to think about it, it is easy to forget to pass it through on every single a job. Using a middleware allows us to think about our job code in a more similar way to our controller code.
2. `tenant_id` - This is kind of similar to the `request_id`. Typically the `tenant_id` gets set early in the request cycle, either via a rack middleware or an `ApplicationController` `before_action`. For many tenacy gems, you don't really need to reference the current `tenant_id` at all once it is set. It takes care of it for you. So again, it is something developers become "trained" not to think about that has to be manually handled every time.
